version: "3.9"

services:
  frontend:
    build:
      context: ./car-frontend
      args:
        BACKEND_URL: http://localhost:3000
    ports:
      - "80:80"
    environment:
      - BACKEND_URL=http://localhost:3000

  backend:
    build:
      context: ./car-shipping
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - MONGODB_URI=mongodb://mongo:27017/car-management
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    command: mongod --storageEngine wiredTiger
