
FROM node:18 AS build

WORKDIR /app/frontend

# Copy the package.json and package-lock.json
COPY package.json yarn.lock ./

# Install the dependencies
RUN yarn install

# Copy the rest of the application
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Serve the React app using an nginx server
FROM nginx:alpine

# Copy the build output to replace the default nginx contents
COPY --from=build /app/frontend/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
