
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm install
RUN npm install --save-dev nodemon

# Bundle app source
COPY . .

# Copy nodemon config
COPY nodemon.json nodemon.json

# Copy .env file
COPY .env .env

RUN npm run seed

EXPOSE 3000
CMD [ "npm", "run", "start:dev" ]
